# Generated by Django 5.2.14 on 2026-07-14 21:49

import siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0047_siteconfiguration_club_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="glider_reservation_time_preferences",
            field=models.JSONField(
                blank=True,
                default=siteconfig.models.default_glider_reservation_time_preferences,
                help_text="Enabled preset time periods for glider reservations. Existing reservations keep their stored period even if a period is later disabled.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="glider_reservation_time_ranges",
            field=models.JSONField(
                blank=True,
                default=siteconfig.models.default_glider_reservation_time_ranges,
                help_text="Clock ranges for preset glider reservation periods, stored as HH:MM values.",
            ),
        ),
    ]
