# Generated by Django 5.2.14 on 2026-07-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0048_siteconfiguration_billing_app_enabled"),
        ("siteconfig", "0048_siteconfiguration_glider_reservation_time_preferences"),
    ]

    operations = []
