# Generated by Django 5.2.16 on 2026-08-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0049_merge_0048_billing_and_reservation_preferences"),
        ("siteconfig", "0051_siteconfiguration_visiting_pilot_max_visits_per_year"),
    ]

    operations = []
