# Generated by Django 5.2.14 on 2026-08-20 17:54

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0026_alter_member_membership_status_visitingpilotvisit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="membership_status",
            field=models.CharField(
                blank=True,
                choices=members.models.get_membership_status_choices,
                default="Non-Member",
                max_length=50,
                null=True,
            ),
        ),
    ]
