# Generated by Django 5.2.16 on 2026-10-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_alter_member_membership_status'),
        ('members', '0029_add_sport_pilot_choice'),
    ]

    operations = [
    ]
